# Generated by Django 4.1.3 on 2022-12-31 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlogBuser",
            fields=[
                ("buser_id", models.AutoField(primary_key=True, serialize=False)),
                ("email", models.CharField(max_length=20)),
                ("nickname", models.CharField(max_length=20)),
                ("password", models.CharField(max_length=20)),
            ],
            options={
                "db_table": "blog_busers",
            },
        ),
    ]
