# Generated by Django 4.1.3 on 2022-12-31 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cinemas", "0001_initial"),
        ("movies", "0001_initial"),
        ("theaters", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MultiplexShowtime",
            fields=[
                ("showtime_id", models.AutoField(primary_key=True, serialize=False)),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                (
                    "multiplex_cinema",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cinemas.multiplexcinema",
                    ),
                ),
                (
                    "multiplex_movies",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="movies.multiplexmovie",
                    ),
                ),
                (
                    "multiplex_theater",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="theaters.multiplextheater",
                    ),
                ),
            ],
            options={
                "db_table": "multiplex_showtimes",
            },
        ),
    ]
