# Generated by Django 4.1.3 on 2022-12-31 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("theaters", "0001_initial"),
        ("showtimes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MultiplexTheaterTicket",
            fields=[
                (
                    "theater_ticket_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("x", models.IntegerField()),
                ("y", models.IntegerField()),
                (
                    "multiplex_showtime",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="showtimes.multiplexshowtime",
                    ),
                ),
                (
                    "multiplex_theater",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="theaters.multiplextheater",
                    ),
                ),
            ],
            options={
                "db_table": "multiplex_theater_tickets",
            },
        ),
    ]
