version: "3.3"

services:
  db:
    container_name: mydb
    build: ./docker/mysql
    restart: always
    tty: true
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: root
    expose:
      - '3306'
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/initdb.d:/docker-entrypoint-initdb.d
      - ./docker/mysql/conf.d:/etc/mysql/conf.d

    networks:
      - local-net

  api:
    links:
      - db
    container_name: "api"
    build: ./docker/api
    ports:
      - "8000:8000"
    volumes:
      - ./code:/usr/src/server
    networks:
      - local-net
networks:
  local-net:
    driver: bridge