# Generated by Django 4.1.3 on 2022-12-31 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("suser", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShopDelivery",
            fields=[
                ("delivery_id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=100)),
                ("detail_address", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=100)),
                (
                    "shop_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="suser.shopsuser",
                    ),
                ),
            ],
            options={
                "db_table": "shop_deliveries",
            },
        ),
    ]
