# Generated by Django 4.1.3 on 2022-12-31 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MultiplexMovie",
            fields=[
                ("movie_id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=100)),
                ("director", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=1000)),
                ("poster_url", models.CharField(max_length=255)),
                ("running_time", models.CharField(max_length=100)),
                ("age_rating", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "multiplex_movies",
            },
        ),
    ]
