# Generated by Django 4.1.4 on 2022-12-27 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cinemas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieTheater',
            fields=[
                ('theater_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('seat', models.TextField()),
                ('movie_cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinemas.moviecinema')),
            ],
            options={
                'db_table': 'movie_theaters',
            },
        ),
    ]
